M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Thu 16 Mar 2023 07:30:07 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-16T19:30:07-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X3.8912Y-3.0512
X4.1668Y-3.0512
T0
M30
